QUESTIONS:
  es:
    presentation:
      - text: ""
    formulaires:
      - question: ""
      - question: ""
      - question: ""
      - question: ""
      - question: ""
      - question: ""
    audio_questions:
      - question: ""
      - question: ""
      - question: ""
      - question: ""
      - question: ""
    conclusion:
      - text: ""
  ca:
    presentation:
      - text: ""
    formulaires:
      - question: ""
      - question: ""
      - question: ""
      - question: ""
      - question: ""
      - question: ""
    audio_questions:
      - question: ""
      - question: ""
      - question: ""
      - question: ""
      - question: ""
    conclusion:
      - text: ""

ERRORS:
  es:
    LANG_NOT_SUPPORTED: "⚠️ Idioma no soportado. Escribe 'ES' o 'CAT'."
    INVALID_NUMBER: "⚠️ Por favor responde con un número entre 0 y 4."
    NOT_AUDIO: "⚠️ La respuesta debe ser un audio 🎙️"
    UNKNOWN_STATE: "⚠️ Estado desconocido. Por favor, empieza de nuevo escribiendo 'ES' o 'CAT'."
    AUDIO_TOO_SHORT: "⚠️ El audio es demasiado corto. Por favor, intenta grabar un audio más largo de almenos 20 segundos."
  ca:
    LANG_NOT_SUPPORTED: "⚠️ Idioma no reconegut. Escriu 'ES' o 'CAT'."
    INVALID_NUMBER: "⚠️ Si us plau, respon amb un número entre 0 i 4."
    NOT_AUDIO: "⚠️ La resposta ha de ser un àudio 🎙️"
    UNKNOWN_STATE: "⚠️ Estat desconegut. Si us plau, comença de nou escrivint 'ES' o 'CAT'."
    AUDIO_TOO_SHORT: "⚠️ L'àudio és massa curt. Si us plau, intenta gravar un àudio més llarg d'almenys 20 segons."
