QUESTIONS:
  es:
    presentation:
      - text: "Hola que tal encantado te voy a ayudar a saber qué haces cada día.\nPrimero eres nuevo en la plataforma? Responde con si o no"
    formulaires:
      - question: "Bienvenido! Cómo te llamas?"
      - question: "Indica una contraseña: "
      - question: "¿Cuál es tu sanimal favorito?"
      - question: "¿Te gustan las mates? ¿En una escala del 0 al 10 siendo 0 concursante de la isla de las tentaciones y 10 tengo a Gauss tatuado en el culo."
    login:
      - question: "Cuál es tu nombre de usuario?"
      - question: "Cuál es tu contraseña?"
    questions:
      - question: "¿Qué día te interesa saber?"
      - question: "¿En qué momento del día?"
      - question: "¿Quieres saber algo más?"
      - question: "¿Quieres un fun fact de tu animal favorito relacionado con tu nivel matemático?"
    conclusion:
      - text: "Bueno pues nada ciao ciao."

